"""PDF export — dual-engine PDF generation integrated with the IdeaClaw pipeline.

Engines (priority order):
  1. WeasyPrint — CSS-based, high-fidelity HTML→PDF
  2. ReportLab — programmatic, no external deps

Integrates with:
  - export.Exporter → called as PdfExporter().export(content, path)
  - export.styles  → uses LaTeX style registry for academic formatting
  - quality.report → includes PQS scores in the audit footer
  - library.personalize → respects user style preferences

Usage:
    from ideaclaw.export.pdf import PdfExporter
    exporter = PdfExporter()
    exporter.export(markdown_content, Path("output.pdf"), metadata={...})
"""

from __future__ import annotations

import html
import logging
import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Dict, List, Optional

logger = logging.getLogger(__name__)

# Engine detection
try:
    import weasyprint  # type: ignore
    HAS_WEASYPRINT = True
except ImportError:
    HAS_WEASYPRINT = False

try:
    from reportlab.lib.pagesizes import A4  # type: ignore
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle  # type: ignore
    from reportlab.platypus import (  # type: ignore
        SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
        PageBreak, Image as RLImage,
    )
    from reportlab.lib.units import mm, cm  # type: ignore
    from reportlab.lib import colors  # type: ignore
    HAS_REPORTLAB = True
except ImportError:
    HAS_REPORTLAB = False


__all__ = ["PdfExporter", "PdfConfig"]


@dataclass
class PdfConfig:
    """PDF generation configuration."""
    engine: str = "auto"           # auto|weasyprint|reportlab|html_fallback
    page_size: str = "A4"
    margin_mm: float = 25.0
    font_family: str = "serif"
    font_size_pt: int = 11
    header_text: str = ""
    footer_text: str = "Generated by IdeaClaw"
    include_toc: bool = True
    include_cover: bool = True
    include_watermark: bool = False
    watermark_text: str = "DRAFT"
    css_theme: str = "academic"    # academic|minimal|modern


# ---------------------------------------------------------------------------
# CSS Themes
# ---------------------------------------------------------------------------

CSS_THEMES = {
    "academic": """\
        @page {
            size: A4;
            margin: 25mm;
            @top-center { content: "%(header)s"; font-size: 9pt; color: #666; }
            @bottom-center { content: "%(footer)s — Page " counter(page); font-size: 9pt; color: #666; }
        }
        body {
            font-family: "Times New Roman", "Noto Serif", serif;
            font-size: 11pt; line-height: 1.6; color: #222;
            max-width: 100%%; margin: 0;
        }
        .cover { text-align: center; padding-top: 120px; page-break-after: always; }
        .cover h1 { font-size: 24pt; margin-bottom: 20px; color: #1a1a2e; }
        .cover .authors { font-size: 14pt; color: #444; margin: 10px 0; }
        .cover .date { font-size: 12pt; color: #888; }
        .cover .abstract { text-align: left; margin: 60px 40px 0; padding: 15px;
                           border-left: 3px solid #0072B2; background: #f8f9fa; font-size: 10pt; }
        h1 { font-size: 18pt; color: #1a1a2e; border-bottom: 2px solid #0072B2;
             padding-bottom: 4px; margin-top: 30px; }
        h2 { font-size: 14pt; color: #16213e; margin-top: 24px; }
        h3 { font-size: 12pt; color: #333; }
        table { border-collapse: collapse; width: 100%%; margin: 12px 0; font-size: 10pt; }
        th, td { border: 1px solid #ccc; padding: 6px 10px; text-align: left; }
        th { background: #0072B2; color: white; font-weight: bold; }
        tr:nth-child(even) { background: #f8f8f8; }
        blockquote { border-left: 3px solid #E69F00; padding: 8px 16px; margin: 12px 0;
                     background: #fffef5; color: #555; font-style: italic; }
        code { background: #f4f4f4; padding: 2px 6px; border-radius: 3px; font-size: 10pt; }
        pre { background: #f4f4f4; padding: 12px; border-radius: 4px; font-size: 9pt;
              overflow-x: auto; white-space: pre-wrap; }
        .watermark { position: fixed; top: 40%%; left: 20%%; font-size: 80pt; color: rgba(200,200,200,0.15);
                     transform: rotate(-45deg); z-index: -1; }
        .toc { page-break-after: always; }
        .toc h2 { border-bottom: 1px solid #ccc; }
        .toc ul { list-style: none; padding-left: 0; }
        .toc li { margin: 4px 0; }
        .pqs-footer { margin-top: 40px; padding-top: 10px; border-top: 1px solid #ddd;
                      font-size: 9pt; color: #999; }
    """,
    "minimal": """\
        @page { size: A4; margin: 20mm; }
        body { font-family: "Helvetica", sans-serif; font-size: 10pt; line-height: 1.5; }
        h1 { font-size: 16pt; } h2 { font-size: 13pt; } h3 { font-size: 11pt; }
        table { border-collapse: collapse; width: 100%%; }
        th, td { border: 1px solid #ddd; padding: 5px 8px; }
    """,
    "modern": """\
        @page { size: A4; margin: 22mm;
            @bottom-center { content: counter(page); font-size: 9pt; } }
        body { font-family: "Inter", "Segoe UI", sans-serif; font-size: 10.5pt;
               line-height: 1.7; color: #333; }
        h1 { font-size: 20pt; color: #0072B2; }
        h2 { font-size: 15pt; color: #16213e; border-left: 4px solid #0072B2; padding-left: 10px; }
        code { background: #e8f4fd; padding: 2px 6px; border-radius: 3px; }
    """,
}


class PdfExporter:
    """PDF exporter integrated with IdeaClaw pipeline.

    Tries WeasyPrint → ReportLab → HTML fallback in order.
    """

    def __init__(self, config: Optional[PdfConfig] = None):
        self.config = config or PdfConfig()
        self._engine = self._resolve_engine()

    def export(
        self,
        pack_content: str,
        output_path: Path,
        metadata: Optional[Dict[str, Any]] = None,
        pqs_scores: Optional[Dict[str, float]] = None,
    ) -> Path:
        """Export pack content as PDF.

        Args:
            pack_content: Markdown content.
            output_path: Path to write PDF.
            metadata: Optional dict with title, authors, abstract, date.
            pqs_scores: Optional quality scores for audit footer.

        Returns:
            Path to the generated PDF.
        """
        output_path.parent.mkdir(parents=True, exist_ok=True)
        metadata = metadata or {}

        logger.info("Exporting PDF via %s engine → %s", self._engine, output_path)

        if self._engine == "weasyprint":
            self._export_weasyprint(pack_content, output_path, metadata, pqs_scores)
        elif self._engine == "reportlab":
            self._export_reportlab(pack_content, output_path, metadata, pqs_scores)
        else:
            self._export_html_fallback(pack_content, output_path, metadata, pqs_scores)

        logger.info("PDF exported: %s (%d bytes)", output_path, output_path.stat().st_size)
        return output_path

    # ---- WeasyPrint engine ----

    def _export_weasyprint(
        self, content: str, output_path: Path,
        metadata: Dict[str, Any], pqs_scores: Optional[Dict[str, float]],
    ) -> None:
        html_str = self._markdown_to_html(content, metadata, pqs_scores)
        doc = weasyprint.HTML(string=html_str)
        doc.write_pdf(str(output_path))

    # ---- ReportLab engine ----

    def _export_reportlab(
        self, content: str, output_path: Path,
        metadata: Dict[str, Any], pqs_scores: Optional[Dict[str, float]],
    ) -> None:
        doc = SimpleDocTemplate(
            str(output_path), pagesize=A4,
            leftMargin=self.config.margin_mm * mm,
            rightMargin=self.config.margin_mm * mm,
            topMargin=self.config.margin_mm * mm,
            bottomMargin=self.config.margin_mm * mm,
        )
        styles = getSampleStyleSheet()
        story: List[Any] = []

        # Cover
        if self.config.include_cover and metadata.get("title"):
            story.append(Spacer(1, 80 * mm))
            story.append(Paragraph(
                f"<font size=24><b>{html.escape(metadata['title'])}</b></font>",
                styles["Title"],
            ))
            if metadata.get("authors"):
                authors = ", ".join(metadata["authors"]) if isinstance(metadata["authors"], list) else metadata["authors"]
                story.append(Paragraph(f"<font size=14>{html.escape(authors)}</font>", styles["Normal"]))
            story.append(Spacer(1, 10 * mm))
            if metadata.get("abstract"):
                story.append(Paragraph(
                    f"<i>{html.escape(metadata['abstract'][:500])}</i>",
                    styles["Normal"],
                ))
            story.append(PageBreak())

        # Content — split by lines and convert to paragraphs
        for line in content.split("\n"):
            stripped = line.strip()
            if not stripped:
                story.append(Spacer(1, 3 * mm))
            elif stripped.startswith("# "):
                story.append(Paragraph(
                    f"<font size=16><b>{html.escape(stripped[2:])}</b></font>",
                    styles["Heading1"],
                ))
            elif stripped.startswith("## "):
                story.append(Paragraph(
                    f"<font size=13><b>{html.escape(stripped[3:])}</b></font>",
                    styles["Heading2"],
                ))
            elif stripped.startswith("### "):
                story.append(Paragraph(
                    f"<font size=11><b>{html.escape(stripped[4:])}</b></font>",
                    styles["Heading3"],
                ))
            elif stripped.startswith("- ") or stripped.startswith("* "):
                story.append(Paragraph(f"• {html.escape(stripped[2:])}", styles["BodyText"]))
            else:
                story.append(Paragraph(html.escape(stripped), styles["BodyText"]))

        # PQS footer
        if pqs_scores:
            story.append(Spacer(1, 10 * mm))
            scores_str = " | ".join(f"{k}: {v:.2f}" for k, v in pqs_scores.items())
            story.append(Paragraph(
                f"<font size=8 color='gray'>Quality: {scores_str}</font>",
                styles["Normal"],
            ))

        doc.build(story)

    # ---- HTML fallback ----

    def _export_html_fallback(
        self, content: str, output_path: Path,
        metadata: Dict[str, Any], pqs_scores: Optional[Dict[str, float]],
    ) -> None:
        html_content = self._markdown_to_html(content, metadata, pqs_scores)
        html_path = output_path.with_suffix(".html")
        html_path.write_text(html_content, encoding="utf-8")
        logger.warning(
            "No PDF engine available. Wrote HTML fallback → %s. "
            "Install weasyprint or reportlab for PDF.", html_path,
        )

    # ---- Shared helpers ----

    def _markdown_to_html(
        self, content: str, metadata: Dict[str, Any],
        pqs_scores: Optional[Dict[str, float]],
    ) -> str:
        """Convert markdown to styled HTML for PDF rendering."""
        cfg = self.config
        theme = CSS_THEMES.get(cfg.css_theme, CSS_THEMES["academic"])
        css = theme % {
            "header": html.escape(cfg.header_text or metadata.get("title", "")),
            "footer": html.escape(cfg.footer_text),
        }

        parts = [f"<html><head><style>{css}</style></head><body>"]

        # Watermark
        if cfg.include_watermark:
            parts.append(f'<div class="watermark">{html.escape(cfg.watermark_text)}</div>')

        # Cover page
        if cfg.include_cover and metadata.get("title"):
            parts.append('<div class="cover">')
            parts.append(f'<h1>{html.escape(metadata["title"])}</h1>')
            if metadata.get("authors"):
                authors = metadata["authors"]
                if isinstance(authors, list):
                    authors = ", ".join(authors)
                parts.append(f'<div class="authors">{html.escape(authors)}</div>')
            if metadata.get("date"):
                parts.append(f'<div class="date">{html.escape(metadata["date"])}</div>')
            if metadata.get("abstract"):
                parts.append(f'<div class="abstract"><b>Abstract.</b> {html.escape(metadata["abstract"])}</div>')
            parts.append("</div>")

        # TOC
        if cfg.include_toc:
            toc = self._extract_toc(content)
            if toc:
                parts.append('<div class="toc"><h2>Contents</h2><ul>')
                for level, title in toc:
                    indent = (level - 1) * 20
                    parts.append(f'<li style="margin-left:{indent}px">{html.escape(title)}</li>')
                parts.append("</ul></div>")

        # Main content — basic markdown→html
        body = self._md_to_html_body(content)
        parts.append(body)

        # PQS footer
        if pqs_scores:
            parts.append('<div class="pqs-footer">')
            parts.append("<b>Quality Scores:</b> ")
            parts.append(" | ".join(f"{k}: {v:.2f}" for k, v in pqs_scores.items()))
            parts.append("</div>")

        parts.append("</body></html>")
        return "\n".join(parts)

    @staticmethod
    def _extract_toc(content: str) -> List[tuple]:
        """Extract table of contents from markdown headings."""
        toc = []
        for line in content.split("\n"):
            m = re.match(r"^(#{1,4})\s+(.+)$", line)
            if m:
                toc.append((len(m.group(1)), m.group(2).strip()))
        return toc

    @staticmethod
    def _md_to_html_body(content: str) -> str:
        """Basic markdown → HTML conversion (no external deps)."""
        lines = content.split("\n")
        html_lines = []
        in_code = False

        for line in lines:
            stripped = line.strip()

            if stripped.startswith("```"):
                if in_code:
                    html_lines.append("</pre>")
                    in_code = False
                else:
                    html_lines.append("<pre>")
                    in_code = True
                continue

            if in_code:
                html_lines.append(html.escape(line))
                continue

            if not stripped:
                html_lines.append("<br>")
            elif stripped.startswith("#### "):
                html_lines.append(f"<h4>{html.escape(stripped[5:])}</h4>")
            elif stripped.startswith("### "):
                html_lines.append(f"<h3>{html.escape(stripped[4:])}</h3>")
            elif stripped.startswith("## "):
                html_lines.append(f"<h2>{html.escape(stripped[3:])}</h2>")
            elif stripped.startswith("# "):
                html_lines.append(f"<h1>{html.escape(stripped[2:])}</h1>")
            elif stripped.startswith("> "):
                html_lines.append(f"<blockquote>{html.escape(stripped[2:])}</blockquote>")
            elif stripped.startswith("- ") or stripped.startswith("* "):
                html_lines.append(f"<li>{html.escape(stripped[2:])}</li>")
            elif stripped.startswith("---"):
                html_lines.append("<hr>")
            elif stripped.startswith("|") and "|" in stripped[1:]:
                cells = [c.strip() for c in stripped.split("|")[1:-1]]
                if all(set(c) <= {"-", ":"} for c in cells):
                    continue  # separator row
                tag = "th" if not html_lines or "<table>" == html_lines[-1] else "td"
                row = "".join(f"<{tag}>{html.escape(c)}</{tag}>" for c in cells)
                if tag == "th" and (not html_lines or html_lines[-1] != "<table>"):
                    html_lines.append("<table>")
                html_lines.append(f"<tr>{row}</tr>")
            else:
                # Inline formatting
                text = html.escape(stripped)
                text = re.sub(r"\*\*(.+?)\*\*", r"<b>\1</b>", text)
                text = re.sub(r"\*(.+?)\*", r"<i>\1</i>", text)
                text = re.sub(r"`(.+?)`", r"<code>\1</code>", text)
                html_lines.append(f"<p>{text}</p>")

        if in_code:
            html_lines.append("</pre>")

        return "\n".join(html_lines)

    def _resolve_engine(self) -> str:
        """Determine which engine to use."""
        pref = self.config.engine
        if pref == "auto":
            if HAS_WEASYPRINT:
                return "weasyprint"
            if HAS_REPORTLAB:
                return "reportlab"
            return "html_fallback"
        if pref == "weasyprint" and HAS_WEASYPRINT:
            return "weasyprint"
        if pref == "reportlab" and HAS_REPORTLAB:
            return "reportlab"
        return "html_fallback"

    @property
    def available_engines(self) -> List[str]:
        """List available PDF engines."""
        engines = ["html_fallback"]
        if HAS_WEASYPRINT:
            engines.insert(0, "weasyprint")
        if HAS_REPORTLAB:
            engines.insert(0, "reportlab")
        return engines
